import { defineStore } from 'pinia'

import { supabase } from 'src/boot/supabase'

export const usePosStore = defineStore('pos', {
  state: () => ({
    products: [],
    categories: [],
    cart: [],
    activeCategory: 'All',
    searchQuery: '',
    loading: false,
    checkoutLoading: false,
    showPaymentDialog: false,
  }),

  getters: {
    filteredProducts: (state) => {
      let filtered = state.products

      // Filter by Category
      if (state.activeCategory && state.activeCategory !== 'All') {
        filtered = filtered.filter((p) => p.category_name === state.activeCategory)
      }

      // Filter by Search
      if (state.searchQuery) {
        const query = state.searchQuery.toLowerCase()
        filtered = filtered.filter(
          (p) =>
            p.item_name.toLowerCase().includes(query) || p.item_code.toLowerCase().includes(query),
        )
      }

      return filtered
    },

    cartTotal: (state) => {
      return state.cart.reduce((total, item) => total + item.line_total, 0)
    },

    cartItemCount: (state) => {
      return state.cart.reduce((count, item) => count + item.quantity, 0)
    },
  },

  actions: {
    async fetchCategories() {
      try {
        const { data, error } = await supabase
          .from('item_categories')
          .select('id, name')
          .eq('is_active', true)
          .order('name')

        if (error) throw error
        this.categories = [{ id: 'all', name: 'All' }, ...data]
      } catch (err) {
        console.error('Error fetching categories:', err)
      }
    },

    async fetchProducts() {
      this.loading = true
      try {
        // Fetch items with their category names
        const { data, error } = await supabase
          .from('items')
          .select(
            `
            *,
            item_categories (name)
          `,
          )
          .eq('is_sales_item', true)
          .eq('is_active', true)

        if (error) throw error

        this.products = data.map((item) => ({
          ...item,
          category_name: item.item_categories?.name || 'Uncategorized',
          price: Number(item.selling_price) || 0,
        }))
      } catch (err) {
        console.error('Error fetching products:', err)
      } finally {
        this.loading = false
      }
    },

    addToCart(product) {
      const existingItem = this.cart.find((item) => item.id === product.id)

      if (existingItem) {
        existingItem.quantity++
        existingItem.line_total = existingItem.quantity * existingItem.price
      } else {
        this.cart.push({
          id: product.id,
          name: product.item_name,
          price: product.price,
          quantity: 1,
          line_total: product.price,
        })
      }
    },

    removeFromCart(productId) {
      const index = this.cart.findIndex((item) => item.id === productId)
      if (index !== -1) {
        this.cart.splice(index, 1)
      }
    },

    updateCartItemQuantity(productId, quantity) {
      const item = this.cart.find((i) => i.id === productId)
      if (item) {
        if (quantity <= 0) {
          this.removeFromCart(productId)
        } else {
          item.quantity = quantity
          item.line_total = item.quantity * item.price
        }
      }
    },

    clearCart() {
      this.cart = []
    },

    async processCheckout(paymentDetails) {
      this.checkoutLoading = true
      try {
        const totalAmount = this.cartTotal

        // 1. Create Invoice
        const { data: invoice, error: invoiceError } = await supabase
          .from('invoices')
          .insert({
            total_amount: totalAmount,
            status: 'paid', // Instant settlement for POS
            payment_method: paymentDetails.method,
            notes: 'POS Transaction',
          })
          .select()
          .single()

        if (invoiceError) throw invoiceError

        // 2. Create Invoice Lines
        const invoiceLines = this.cart.map((item) => ({
          invoice_id: invoice.id,
          item_id: item.id,
          quantity: item.quantity,
          unit_price: item.price,
          // line_total is generated by DB
        }))

        const { error: linesError } = await supabase.from('invoice_lines').insert(invoiceLines)

        if (linesError) throw linesError

        // Success - Clear cart and return success
        this.clearCart()
        return { success: true, invoiceId: invoice.id }
      } catch (err) {
        console.error('Checkout failed:', err)
        return { success: false, error: err.message }
      } finally {
        this.checkoutLoading = false
      }
    },
  },
})
